language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.1.100
branches:
  only:
    - main
    - staging
before_script:
  - chmod -R a+x scripts
  - chmod -R a+x src
script:
  - dotnet build -c release
  - dotnet test
  - ./scripts/pack.sh
notifications:
  email:
    on_success: never
    on_failure: always